Allow users to switch between color and linetype aesthetics
pharmaverse/ggsurvfit pull request #172
Opened 2023-10-04 02:39 UTC by ddsjoberg

**What changes are proposed in this pull request?**
* By default, a model plot created with `ggsurvfit()` or `ggcuminc()` uses the color aesthetic to plot curves by the stratifying variable(s), and further, `ggcuminc()` uses the linetype aesthetic for plots that contain multiple outcomes (i.e. competing events). We not introduce the global option `"ggsurvfit.switch-color-linetype"` to switch these defaults, giving users more flexibility over the output figures. (#166)

**If there is an GitHub issue associated with this pull request, please provide link.**
closes #166

--------------------------------------------------------------------------------

Reviewer Checklist (if item does not apply, mark as complete)

- [ ] Ensure all package dependencies are installed by running `renv::install()`
- [ ] PR branch has pulled the most recent updates from master branch. Ensure the pull request branch and your local version match and both have the latest updates from the master branch.
- [ ] If a new function was added, function included in `_pkgdown.yml`
- [ ] If a bug was fixed, a unit test was added for the bug check
- [ ] Run `pkgdown::build_site()`. Check the R console for errors, and review the rendered website.
- [ ] Overall code coverage remains >99.5%. Review coverage with `withr::with_envvar(new = c("NOT_CRAN" = "true"), covr::report())`. Begin in a fresh R session without any packages loaded. 
- [ ] R CMD Check runs without errors, warnings, and notes
- [ ] `usethis::use_spell_check()` runs with no spelling errors in documentation

When the branch is ready to be merged into master:
- [ ] Update `NEWS.md` with the changes from this pull request under the heading "`# ggsurvfit (development version)`". If there is an issue associated with the pull request, reference it in parentheses at the end update (see `NEWS.md` for examples).
- [ ] Increment the version number using `usethis::use_version(which = "dev")` 
- [ ] Run `codemetar::write_codemeta()`
- [ ] Run `usethis::use_spell_check()` again
- [ ] Approve Pull Request
- [ ] Merge the PR. Please use "Squash and merge".

2023-10-04 17:20 UTC, psoldath approved these changes
@ddsjoberg Thank you for implementing the request!

The code works perfect! When calling the global option options("ggsurvfit.switch-color-linetype" = TRUE), outcome and strata are switched like requested.

However, I don't know if I tested it correctly? I am very new to R, but I made it work by replacing the old code with the new code using the trace() function in the following functions:
trace(ggsurvfit:::.construct_censor_mark_aes, edit = TRUE)
trace(ggsurvfit:::.match_strata_level_to_color, edit = TRUE)
trace(ggsurvfit:::.construct_aes, edit = TRUE)
trace(ggsurvfit:::print.ggsurvfit, edit = TRUE)

2023-10-10 01:09 UTC, psoldath approved these changes

2023-10-10 01:13 UTC, psoldath approved these changes

2023-10-10 01:17 UTC, psoldath commented
@ddsjoberg I download the pull request and the code works perfectly! Thank you for implementing the request.

2023-10-10 01:47 UTC, ddsjoberg commented
Great! We'll merge this when @timtreis, a package co-author, has completed the review!

2023-10-10 09:07 UTC, timtreis commented on NEWS.md
> +* By default, a model plot created with `ggsurvfit()` or `ggcuminc()` uses the color aesthetic to plot curves by the stratifying variable(s), and further, `ggcuminc()` uses the linetype aesthetic for
We >now< introduce...

2023-10-10 09:08 UTC, timtreis commented on R/add_risktable_strata_symbol.R
>    # what modifications could a use make the the figures that could break this connection?
Is this comment still needed? Also, type in the comment (use -> user)

2023-10-10 09:15 UTC, timtreis requested changes
Minor typos, potentially unneccecary comments. Good example that illustrate functionality which work. Tests pass, but some paths are too long? Do you care within `ggsurvfit`?

```
   Found the following non-portable file paths:
     ggsurvfit/tests/testthat/_snaps/add_risktable_strata_symbol/add-risktable-strata-symbol-circle.new.svg
     ggsurvfit/tests/testthat/_snaps/add_risktable_strata_symbol/add-risktable-strata-symbol-default.new.svg
   
   Tarballs are only required to store paths of up to 100 bytes and cannot
   store those of more than 256 bytes, with restrictions including to 100
   bytes for the final component.
   See section ‘Package structure’ in the ‘Writing R Extensions’ manual.
   
   ```
   
Package Check works for me, vdiffr fails for some reason which I assume is Operating System + Version stuff, manually compared a large amount of snapshots and they were all the same.

2023-10-10 14:53 UTC, ddsjoberg commented on NEWS.md
> +* By default, a model plot created with `ggsurvfit()` or `ggcuminc()` uses the color aesthetic to plot curves by the stratifying variable(s), and further, `ggcuminc()` uses the linetype aesthetic for
ahh, thank you! updated

2023-10-10 14:55 UTC, ddsjoberg commented on R/add_risktable_strata_symbol.R
>    # what modifications could a use make the the figures that could break this connection?
oh yes, that is an oldie...no longer needed, good catch!

2023-10-10 15:18 UTC, ddsjoberg commented
Thank you @timtreis for the thorough review!

vdiffr began failing everywhere (except locally) recently. I've since turned these off on GH Actions. I hope they begin working again. Previously, we had set to only run the vdiffr tests when the R version matched the current release of R and the check was being run on the same OS I develop on to avoid those kinds of failures on Linux.

I am sure if you looked at the differences in the failing vdiffr tests, there wouldn't be anything importantly different.

2023-10-10 17:03 UTC, merged